apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::162426944129:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1Q097HIJGSAS1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::162426944129:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-08T13:22:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1608"
  uid: 03e059c6-e588-4d16-a92b-55dcb3dc74e5
